name: Upload Website

on:
  push:
    branches:
    - Desarrollo

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: build
      uses: addnab/docker-run-action@v3
      with: 
        image: node:alpine
        options: -v ${{ github.workspace}}:/react-app
        run: cd /react-app && apk add yarn && yarn add -D webpack-cli && yarn build
       
    - name: check dir
      run: ls 
     
    - name: deploy 
      uses: ./ 
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}        
 test:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - name: Check out Git repositor
     uses: actions/checkout@v3  
   - name: Create Dir
     run: |
        mkdir Tests
      
   - name: Install
     uses: actions/setup-node@v3
     with:
        node-version: '16.x' 
            
   - name: Install Newman
     run: | 
        npm install -g newman
        npm install -g newman-reporter-htmlextra
          
   - name: Run Test     
     run : newman run "shipping.postman_collection.json" -r cli,htmlextra --reporter-htmlextra-export Tests/htmlreport.html
       
   - name:  Reporte
     uses: actions/upload-artifact@v3
     with:
       name: Reports
       path: Tests   
